
USE Gr8BnBApplication;

SELECT * FROM User;
SELECT * FROM Host;
SELECT * FROM Guest;
SELECT * FROM Review;
SELECT * FROM HostRating;

SELECT COUNT(*) FROM User;
SELECT COUNT(*) FROM Host;
SELECT COUNT(*) FROM Guest;
SELECT COUNT(*) FROM Review;
SELECT COUNT(*) FROM HostRating;
